# Generated by Django 4.1.1 on 2022-09-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("category", models.CharField(max_length=40)),
                ("type_product", models.CharField(max_length=30)),
            ],
        ),
    ]
